In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("Crop_recommendation in csv.csv",header=0)

In [3]:
dataset

N   P   K  temperature   humidity        ph    rainfall    Crop
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

In [4]:
dataset.describe()

N            P            K  temperature     humidity  \
count  2200.000000  2200.000000  2200.000000  2200.000000  2200.000000   
mean     50.551818    53.362727    48.149091    25.616244    71.481779   
std      36.917334    32.985883    50.647931     5.063749    22.263812   
min       0.000000     5.000000     5.000000     8.825675    14.258040   
25%      21.000000    28.000000    20.000000    22.769375    60.261953   
50%      37.000000    51.000000    32.000000    25.598693    80.473146   
75%      84.250000    68.000000    49.000000    28.561654    89.948771   
max     140.000000   145.000000   205.000000    43.675493    99.981876   

                ph     rainfall  
count  2200.000000  2200.000000  
mean      6.469480   103.463655  
std       0.773938    54.958389  
min       3.504752    20.211267  
25%       5.971693    64.551686  
50%       6.425045    94.867624  
75%       6.923643   124.267508  
max       9.935091   298.560117

In [5]:
dataset.columns

Index(['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'Crop'], dtype='object')

In [6]:
x=dataset[['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall']]

In [7]:
y=dataset["Crop"]

In [8]:
x

N   P   K  temperature   humidity        ph    rainfall
0      90  42  43    20.879744  82.002744  6.502985  202.935536
1      85  58  41    21.770462  80.319644  7.038096  226.655537
2      60  55  44    23.004459  82.320763  7.840207  263.964248
3      74  35  40    26.491096  80.158363  6.980401  242.864034
4      78  42  42    20.130175  81.604873  7.628473  262.717340
...   ...  ..  ..          ...        ...       ...         ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507
2196   99  15  27    27.417112  56.636362  6.086922  127.924610
2197  118  33  30    24.131797  67.225123  6.362608  173.322839
2198  117  32  34    26.272418  52.127394  6.758793  127.175293
2199  104  18  30    23.603016  60.396475  6.779833  140.937041

[2200 rows x 7 columns]

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
le=LabelEncoder()

In [11]:
le_final=le.fit_transform(y)

In [12]:
le_final

array([20, 20, 20, ...,  5,  5,  5])

In [13]:
len(le_final)

2200

In [14]:
#for getting the label of each crop 
def storage():
 
    print("rice -->",le_final[5])
    print("maize -->",le_final[105])
    print("chickpae -->",le_final[205])
    print("kidneybeans -->",le_final[305])
    print("pegionpeas -->",le_final[405])
    print("mothbeans -->",le_final[505])
    print("mungbean -->",le_final[605])
    print("blackgram -->",le_final[705])
    print("lentil -->",le_final[805])
    print("pomegranate -->",le_final[905])
    print("banana -->",le_final[1005])
    print("mango -->",le_final[1105])
    print("grapes -->",le_final[1205])
    print("watermelon -->",le_final[1305])
    print("muskmelon -->",le_final[1405])
    print("apple -->",le_final[1505])
    print("orange -->",le_final[1605])
    print("papaya -->",le_final[1705])
    print("coconut -->",le_final[1805])
    print("cotton -->",le_final[1905])
    print("jute -->",le_final[2005])
    print("coffee -->",le_final[2105])
   


storage()

rice --> 20
maize --> 11
chickpae --> 3
kidneybeans --> 9
pegionpeas --> 18
mothbeans --> 13
mungbean --> 14
blackgram --> 2
lentil --> 10
pomegranate --> 19
banana --> 1
mango --> 12
grapes --> 7
watermelon --> 21
muskmelon --> 15
apple --> 0
orange --> 16
papaya --> 17
coconut --> 4
cotton --> 6
jute --> 8
coffee --> 5


In [15]:
from sklearn.model_selection import train_test_split

In [16]:
 x_train, x_test, y_train, y_test = train_test_split(x, le_final, test_size=0.40, random_state=42)

In [17]:
x_train

N    P    K  temperature   humidity        ph    rainfall
208    42   62   75    18.179123  18.904269  7.010571   81.849975
1641    0   23   15    22.566642  93.374889  7.598729  109.858575
881     9   56   17    26.137083  66.772921  6.261938   46.482807
720    58   71   15    27.825928  67.586188  6.919244   74.012297
1017  109   79   45    27.667528  79.685428  6.490074  108.664640
...   ...  ...  ...          ...        ...       ...         ...
1638   10    5    5    21.213070  91.353492  7.817846  112.983436
1095  108   94   47    27.359116  84.546250  6.387431   90.812505
1130   11   36   31    27.920633  51.779659  6.475449  100.258567
1294   11  124  204    13.429886  80.066340  6.361141   71.400430
860    32   78   22    23.970814  62.355576  7.007038   53.409060

[1320 rows x 7 columns]

In [18]:
x_test

N    P    K  temperature   humidity        ph    rainfall
1451  101   17   47    29.494014  94.729813  6.185053   26.308209
1334   98    8   51    26.179346  86.522581  6.259336   49.430510
1761   59   62   49    43.360515  93.351916  6.941497  114.778071
1735   44   60   55    34.280461  90.555616  6.825371   98.540477
1576   30  137  200    22.914300  90.704756  5.603413  118.604465
...   ...  ...  ...          ...        ...       ...         ...
1839   14   21   35    29.525014  91.911853  6.121006  194.310027
236    57   58   77    18.726494  17.584064  7.978997   81.201765
551    22   42   22    25.542491  56.966408  7.887659   48.467970
520    11   44   17    26.340433  55.591604  8.016211   35.105120
1261   22  133  201    23.819957  80.122116  6.002996   67.273986

[880 rows x 7 columns]

In [19]:
x_train.shape

(1320, 7)

In [20]:
y_train

array([ 3, 16, 10, ..., 12,  7, 10])

In [21]:
from sklearn.linear_model import LogisticRegression

In [22]:
model=LogisticRegression(max_iter=1000)

In [23]:
model.fit(x_train,y_train)

E:\VISUAL STUDIO CODE\Anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=1000)

In [24]:
war=model.predict(x_test)#banana


In [25]:
# if war==1:
#     print('banana')
# elif war==2:
#     print('blackgram')
# elif war==2:
#     print('blackgram')
# elif war==2:
#     print('blackgram')
# elif war==2:
#     print('blackgram')
# elif war==2:
#     print('blackgram')

In [26]:
# type(war)

In [27]:
model.predict([[80,26,55,24.5,88.9,6.14,49.1]])
#80	26	55	24.53442564	88.989272	6.140099215	49.11618732


E:\VISUAL STUDIO CODE\Anaconda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([21])

In [28]:
war=model.predict([[90,92,55,27.00932084,80.18546798,6.13465588,97.32531705]])
print(war)
if war==1:
    print('banana')

[1]
banana


E:\VISUAL STUDIO CODE\Anaconda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [29]:
model.predict([[101,17,47,29,94,6,26]])


E:\VISUAL STUDIO CODE\Anaconda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([15])

In [30]:
model.predict([[126,37,21,25.84997269,84.16855231,6.61448588,79.03421249]])#cotton

E:\VISUAL STUDIO CODE\Anaconda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([6])

In [31]:
y_pred=model.predict(x_test)

In [32]:
 (y_pred)

array([15, 21, 17, 17,  0, 12,  0, 13, 14, 10,  2,  4, 19,  8,  4, 19,  0,
        6, 17, 15,  5, 17, 16, 17,  3,  8, 14, 16, 18, 20, 19, 13,  8, 10,
        8,  2,  8,  3,  3,  9, 17, 12,  2, 11, 14, 11, 18,  4, 15, 11,  2,
        5,  7, 14,  5,  9,  6,  0,  1, 10, 21,  4, 10, 16, 17,  2, 16, 20,
       15, 18, 15,  4,  8,  1,  2, 17,  1,  6, 21, 16,  5,  3, 20, 13, 16,
       12,  5, 13,  2, 19, 11, 13,  6, 17, 18, 13,  9,  5,  2, 10,  4,  8,
       16, 15, 21,  9, 21,  1, 18, 13,  1,  8,  6, 19, 18,  3, 11,  4, 19,
       20, 18,  7,  2,  4,  3, 13,  4, 11,  1, 13,  1,  9, 19,  3,  4, 16,
       18,  1,  1,  0,  9, 15, 14, 13,  4, 11,  0,  4,  9,  2, 14, 10, 21,
       14,  2, 18, 18,  9, 11,  8,  3,  0, 16,  6, 20,  4,  7, 10, 21,  7,
        7,  2, 19,  3,  4, 11, 10,  7, 21,  8,  5,  5,  9,  8, 13,  9,  1,
        9,  4, 17, 17, 14, 12, 19, 21,  9, 11,  0,  2,  3,  7,  7,  1,  6,
       20, 19, 14,  1,  8, 14, 11,  3,  3,  3,  0, 20,  9, 17,  5,  2,  9,
       12, 12,  4, 17,  0

In [33]:
from sklearn.metrics import confusion_matrix

In [34]:
confusion_matrix(y_test,y_pred)

array([[48,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0, 36,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0, 34,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  1,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 47,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 43,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 39,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 37,  0,  0,  0,  0,  3,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 36,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  1,  0,  0, 37,  0,  0,  0,  0,  0,  0,  0,
         0,  1,  0,  0,  4,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 45,  0,  0,

In [35]:
#y_pred

In [ ]:
#|y_test

In [ ]:
import joblib

In [ ]:
joblib.dump(model,'new_web')

In [ ]:
import numpy

In [ ]:
value=[1,16,21,29]

In [ ]:
x=numpy.std(value)

In [ ]:
x

In [ ]:
loaded_data = joblib.load('model_utf8.joblib')

print("Loaded Data:", loaded_data)